// <auto-generated />
using Acc.Services.ProductAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Acc.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220717104137_SeedProducts")]
    partial class SeedProducts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Acc.Services.ProductAPI.Models.Dto.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "CPU",
                            Description = "5.2 GHz, 30MB, BOX, LGA1700, Alder Lake",
                            ImageUrl = "https://microdev.blob.core.windows.net/acc/LD0005914951_1.png",
                            Name = "Intel Core i9 12900F",
                            Price = 580.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "CPU",
                            Description = "Vermeer 3.7 GHz, 12 Cores/24 Threads, No GPU, AM4 (100-000000061), oem ",
                            ImageUrl = "https://microdev.blob.core.windows.net/acc/6158112776.jpg",
                            Name = "AMD Ryzen 9 5900X",
                            Price = 500.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "CPU",
                            Description = "Vermeer 3.4 GHz, 16 Cores/32 Threads, No GPU, AM4 (100-000000061), oem ",
                            ImageUrl = "https://microdev.blob.core.windows.net/acc/6158112776.jpg",
                            Name = "AMD Ryzen 9 5950X",
                            Price = 700.0
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "RAM",
                            Description = "5600Mhz Fury (KF556C40BB-16)",
                            ImageUrl = "https://microdev.blob.core.windows.net/acc/Fury.jpg",
                            Name = "Kingston DDR5 16GB",
                            Price = 165.0
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryName = "RAM",
                            Description = "2666Mhz ",
                            ImageUrl = "https://microdev.blob.core.windows.net/acc/crucial.jpg",
                            Name = "Crucial  DDR4  16GB",
                            Price = 53.0
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryName = "RAM",
                            Description = "4400Mhz (8*2) RGB Memory (GP-ARS16G44)",
                            ImageUrl = "https://microdev.blob.core.windows.net/acc/operativnaya_pamyat_gigabyte_ddr4_16gb_2x8gb_4400mhz_pc_35200_aorus_rgb_led_gp_ars16g44__1460258_1.jpg",
                            Name = "Aorus DDR4 16GB",
                            Price = 140.0
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryName = "GPU",
                            Description = "GAMEROCK PRO GDDR6 320bit 3 - DP HDMI LHR",
                            ImageUrl = "https://microdev.blob.core.windows.net/acc/palit.jpg",
                            Name = "Palit 12GB GeForce RTX3080Ti",
                            Price = 1300.0
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryName = "GPU",
                            Description = "Gaming X Trio LHR",
                            ImageUrl = "https://microdev.blob.core.windows.net/acc/02-msi-geforce-rtx-3070-gaming-x-trio.jpg",
                            Name = "MSI 12GB GeForce RTX3080Ti",
                            Price = 1300.0
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryName = "GPU",
                            Description = "VISION OC GV-N308TVISION OC-12GD",
                            ImageUrl = "https://microdev.blob.core.windows.net/acc/gigabyte.jpg",
                            Name = "Gigabyte-12GB GeForce RTX 3080Ti",
                            Price = 1300.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
